name: Deploy terraform resources

on:
  workflow_dispatch: {}

jobs:
  validate-resources:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Show Apply plan
        run: terraform plan -no-color

      - name: Terraform apply
        run: terraform apply -auto-approve
